### ISSUE TITLE
heartbeat says "Server is ALIVE" even if Apache is stopped

### ISSUE THREAD

**Issue by ndunand** [brendanheywood/moodle-tool_heartbeat#8]
Obviously, this was discovered running the index.php script via CLI.

**Comment by brendanheywood** [comment]
If you call it from a cli, there is no consistent way you can know can know if you are being served correctly to the outside world. There could be multiple layers of caches eg varnish, load balancers etc or different front ends in the brew, and you may not even be able to curl to your self because of funky routing rules. This is designed to either be used as a front end test, or only as a test for the moodle services connections eg sitedata and db. So sorry but closing as wontfix.

**Comment by ndunand** [comment]
That's true, there's no way to account for everything. I would have thought that using something like `curl $CFG->wwwroot.'/.../tool/heartbeat'` would be a small step but it's your call of course.

**Comment by brendanheywood** [comment]
The curl method will fail or give false positives in lots or even most cases. If you curl and go back over the network you may end up back at a different front end behind a load balancer, so the node you are running the command on is failing but you get back an ok. And there a bunch of other similar crazy things we've had to deal with.

**Comment by ndunand** [comment]
Right, indeed better leave it if can't be addresses in a satisfying manner
